services:
  database:
    container_name: database
    image: mariadb:10.5.25
    volumes:
      - ./database/db/database:/var/lib/mysql
      - ./database/db/init.cnf:/etc/mysql/init.cnf
    ports:
      - ${DB_PORT}:3306
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    restart: always

  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin
    image: phpmyadmin:5.2.0-apache
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    restart: always
